import { Inter_Tight } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import Faqs from "@/Components/Faqs";
import WhatsAppButton from "@/Components/WhatsAppButton";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dakshayani",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${interTight.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Header />
        {children}
        <Faqs />
        <Footer />
        <WhatsAppButton />
      </body>
    </html>
  );
}